### ISSUE TITLE
Fulltext XML extraction should look for ids

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsdata#34]
This is here so we don't forget: the fulltext XML extraction pipeline should look for interesting things such as dataset ids.  They appear this way in the IOP fulltext:
```
<named-content content-type="dataset" xlink:href="ADS/Sa.CXO#Obs/11456">11456</named-content>
```
Something for Jonny to do when he reviews the pipeline code...

**Comment by csgrant00** [comment]
On 1/7/15 9:06 AM, Alberto Accomazzi wrote:
>
> This is here so we don't forget: the fulltext XML extraction pipeline 
> should look for interesting things such as dataset ids. They appear 
> this way in the IOP fulltext:
>
> 11456
>
> Something for Jonny to do when he reviews the pipeline code...
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/adsabs/adsdata/issues/34>.
>


Right, MNRAS was also interested in tagging datasets in fulltext...

--Carolyn
*************************************************************************
        Carolyn Stern Grant              Astrophysics Data System (ADS)
        stern@cfa.harvard.edu            Center for Astrophysics
        617-495-7154 (voicemail)         60 Garden Street  MS 83
        617-495-7356 fax                 Cambridge, MA  02138
*************************************************************************

**Comment by aaccomazzi** [comment]
Just a clarification: the dataset id that we want extracted is the content of the "href" attribute below:
```
<named-content content-type="dataset" xlink:href="ADS/Sa.CXO#Obs/11456">11456</named-content>
```
Which represents the URN of the dataset.

**Comment by jonnybazookatone** [comment]
No problem, I'll change it now.

**Comment by jonnybazookatone** [comment]
https://github.com/adsabs/adsdata/pull/41

**Comment by jonnybazookatone** [comment]
This is implemented in the new pipeline adsabs/ADSfulltext. For any issues, place them in that repository.
