### ISSUE TITLE
Jenkins testing

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/adsdata#39]
Needs to be fixed or removed and replaced by Travis CI. Any preferences? Given the TravisCI tests are running fine, I don't see the benefit of having the Jenkins tests - if someone knows better then please let me know

**Comment by romanchyla** [comment]
I would have slight preference for Travis, it is much more agile and
transparent

Jenkins is good for heavy stuff though

**Comment by adsabs-beer-user** [comment]
I vote for Travis whenever possible. Makes pull requests much more
manageable. So yes, let's do that for adsdata.

Alberto

**Comment by jonnybazookatone** [comment]
I'll turn off the build in Jenkins so we don't get spammed every time a pull request is merged.
