### ISSUE TITLE
Review fields incorporated in adsdata 'docs' collection

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsdata#43]
Some of the fields which are merged in docs aren't necessary.  For instance, we still have a "full" field which probably contains stale data pulled I assume from the fulltext collection.  Best way to winnow this down is to see what is used by the ADSimportpipeline, then check with @ehenneken to be sure no other fields are needed.

**Comment by jonnybazookatone** [comment]
So from ADSImportpipeline it needs:

  1. citations
  1. boost
  1. norm_cites
  1. grants
  1. readers
  1. simbad_objects

@ehenneken are there other fields you would need?

**Comment by ehenneken** [comment]
I don't use the 'docs' collection for anything. For the construction of the 'metrics_data' collection I use all the raw 'adsdata' collections (like 'references', 'citations', 'reads', etc etc).

**Comment by aaccomazzi** [comment]
Thanks.  One thing that @ehenneken suggested was to have references included in the docs collection so that we would index them from there rather than the ADSimportpipeline.  I have some reservations about it and I'd like to have a group discussion about this so that we can think this through.

**Comment by aaccomazzi** [comment]
Also, we should change the code (build_docs.py) so that the only fields used to create records in the docs collection are the ones which we need.  This should speed things up and also reduce the overall size of the database.

**Comment by jonnybazookatone** [comment]
See PR #46.
