### ISSUE TITLE
Review collections stored in 'adsdata'

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsdata#44]
We have over 30 collections in the adsdata database, some of which are being periodically updated, but some of which are probably quite stale.  @jonnybazookatone and @ehenneken should review them and make a list of what should stay, then we can zilch the rest.

**Comment by jonnybazookatone** [comment]
Is this not a duplication of issue #43?

**Comment by aaccomazzi** [comment]
Not really: #43 is about "fixing" the docs collection, and figuring out its dependencies.
This issue is about cleaning up the entire adsdata database, removing any non-needed collections.  Related yes, the same, no.

**Comment by jonnybazookatone** [comment]
So, as far as I know, these are the services that require certain collections:

 1. ADSImportpipeline, which is dependent on the docs collection, built by build_docs.py, which should be decided in issue #43.
 1. what is needed by the metrics used by @ehenneken (all of the collections, or?)

Are there any other services that access the mongodb generated by adsdata @aaccomazzi? 

In the end we are changing  sync_mongo_data.py, which syncs the ads classic content with the adsdata mongodb.

**Comment by ehenneken** [comment]
BEER uses 'adsdata' minimally:

    autocomplete/views.py:from flask.ext.adsdata import adsdata
    autocomplete/views.py:        coll = adsdata.get_collection('bibstems_ranked')
    bibutils/utils.py:from flask.ext.adsdata import adsdata 
    bibutils/utils.py:                doc = adsdata.get_metrics_data(bibcode, manipulate=False)

I'm currently creating a Google spreadsheet to have an overview which collection is used by what (if at all).

**Comment by ehenneken** [comment]
With the assumption that we no longer store full text (including acknowledgements) in the 'docs' collection, the following collections are not used to build either the 'docs' collection or the 'metrics_data' collection:

    accnos
    ads_test
    adsdata_test
    adsdata_test_load
    bibstem
    bibstems
    bibstems_ranked (but used in autocompletion in BEER (Pub/Vol/Page))
    eprint_mapping
    eprint_matches
    fulltext
    fulltext_links
    simbad_object_ids
    simbad_objects
    tmp.mr.grants_load_152
    tmp.mr.grants_load_152_inc

**Comment by aaccomazzi** [comment]
Note: since we don't need to process *all* bibcodes, but just the canonical ones, a better list to run build_docs on is the file: $ADS_ABSCONFIG/bibcodes.list.can, which includes only canonical ones. This also solves #45

**Comment by aaccomazzi** [comment]
@ehenneken: let's review the list of collections from your google doc and close the issue please.

**Comment by jonnybazookatone** [comment]
I believe this is the list from Edwin:

* accnos
* ads_test
* adsdata_test
* adsdata_test_load
* bibstem
* bibstems
* bibstems_ranked (but used in autocompletion in BEER (Pub/Vol/Page))
* eprint_mapping
* eprint_matches
* fulltext
* fulltext_links
* simbad_object_ids
* tmp.mr.grants_load_152
* tmp.mr.grants_load_152_inc

ADSData has been updated in PR #47. Once issue #45 is closed, these collections can be *nuked*.

**Comment by ehenneken** [comment]
I'll leave `bibstems_ranked` in place, as it is used for autocompletetion in BEER

**Comment by jonnybazookatone** [comment]
* accnos
* ads_test
* adsdata_test
* adsdata_test_load
* bibstem
* bibstems
* eprint_mapping
* eprint_matches
* fulltext
* fulltext_links
* simbad_object_ids
* tmp.mr.grants_load_152
* tmp.mr.grants_load_152_inc

**Comment by jonnybazookatone** [comment]
I've decided to keep accnos for now for deletions.py. The final list is deleted should be the following:

* ads_test
* adsdata_test
* adsdata_test_load
* bibstem
* bibstems
* eprint_mapping
* eprint_matches
* fulltext
* fulltext_links
* simbad_object_ids
* tmp.mr.grants_load_152
* tmp.mr.grants_load_152_inc
