### ISSUE TITLE
Eliminate processing of preprint records matched to published bibcodes

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/adsdata#45]
Because in the end whatever fields adsdata aggregates for them is not used in any way (the merger disregards them as there is no corresponding canonical bibcode).

This suggests that adsdata should only care about canonical records as it reads data from disk.  I'm 99% sure that right now all bibcodes are ingested.

**Comment by csgrant00** [comment]
On 4/3/15 5:33 PM, Alberto Accomazzi wrote:
>
> Because in the end whatever fields adsdata aggregates for them is not 
> used in any way (the merger disregards them as there is no 
> corresponding canonical bibcode).
>
> This suggests that adsdata should only care about canonical records as 
> it reads data from disk. I'm 99% sure that right now all bibcodes are 
> ingested.
>
>

What about incorporating abstracts and references from preprints where
the published is lacking?

--Carolyn
*************************************************************************
        Carolyn Stern Grant              Astrophysics Data System (ADS)
        stern@cfa.harvard.edu            Center for Astrophysics
        617-495-7154 (voicemail)         60 Garden Street  MS 83
        617-495-7356 fax                 Cambridge, MA  02138
*************************************************************************

**Comment by aaccomazzi** [comment]
@csgrant00: metadata, references and fulltext for eprints matched to published papers is handled automatically by ADSExports, so this won't be a problem.

**Comment by jonnybazookatone** [comment]
There is no pull request for this feature, I will just update it on the production version of ADSData by using the flag '-i' in the build_docs.py call, such that we specify the source file of the bibcodes.
