### ISSUE TITLE
need to check values for correctly formatted html

### ISSUE THREAD

**Issue by romanchyla** [adsabs/adsdata#59]
certain fields should be displayed in bbb without escaping, to do that, we need to make sure that the markup is correct (not to break the site) - ie. we should run the field value through lxml

the fiels are:

 -abstract
 -pub(lication)

possibly some others?

**Comment by jonnybazookatone** [comment]
ADSimportpipeline takes these fields straight from adspy as far as I can tell: https://github.com/adsabs/ADSimportpipeline/blob/master/lib/SolrUpdater.py#L134

So unless you're more specific, I don't think adsdata is the place for this ticket - maybe adspy is more appropriate? @aaccomazzi

**Comment by jonnybazookatone** [comment]
Moved to adsabs/ADSimportpipeline/issues/102.
