### ISSUE TITLE
incomplete updates

### ISSUE THREAD

**Issue by ehenneken** [adsabs/adsdata#63]
Because of the "return" in
```
https://github.com/adsabs/adsdata/blob/master/adsdata/psql_session.py#L63
```
remaining bibcodes in the list `records` get skipped once an unchanged entry in the database is found. This should be a `continue` to just skip this unchanged record.

**Comment by jonnybazookatone** [comment]
Was this fixed in PR #62?

**Comment by jonnybazookatone** [comment]
@ehenneken poke

**Comment by ehenneken** [comment]
yes, this was fixed
